import type { Metadata } from "next";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
import { SiteChrome } from "@/components/site-chrome";


export const metadata: Metadata = {
  title: "Solix",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en">
      <body className="">
        <SiteChrome>{children}</SiteChrome>    
      </body>
    </html>
  );
}
